apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-deploy
  labels:
    component: products-api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: widgetario
      component: products-api
  template:
    metadata:
      labels:
        app: widgetario
        component: products-api
    spec:
      containers:
        - name: products-api-container
          image: 'widgetario/products-api:21.03'
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: secret
              mountPath: /app/config/db
      volumes:
        - name: config
          configMap:
            name: products-api-app-prop
        - name: secret
          secret:
            secretName: products-api-db-app-prop