apiVersion: v1
kind: Service
metadata:
 name: products-db     # The Service uses the domain name numbers-api.
spec:
  selector:
    component: product-db
    app: widgetario
  ports:
   - port: 5432
    #  Traffic is routed to Pods with this label.
  type: ClusterIP       #  This Service is available only to other Pods.