apiVersion: v1
kind: Pod
metadata:
  name: products-api
  labels:
    app: widgetario
    component: products-api
spec:
  containers:
    - name: products-api-container
      image: widgetario/products-api:21.03
      volumeMounts:
        - name: config
          mountPath: "/app/config"
        - name: secret
          mountPath: "/app/config/db"

  volumes:
    - name: config
      configMap:
        name: products-api-app-prop
    - name: secret
      secret:
        secretName: products-api-db-app-prop
