apiVersion: v1
kind: Pod
metadata:
  name: stock-api
  labels:
    app: widgetario
    component: stock-api
spec:
  containers:
    - name: stock-api-container
      image: widgetario/stock-api:21.03
      env:
        - name: POSTGRES_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: stocks-api-db-conn-str
              key: POSTGRES_CONNECTION_STRING


